# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 067015122ee53259762ec91eeebe9189a598a42f06c3b5c191a156f7e551d161c03a4bf2413f130bca94103b058e99304dcbaa2309f26cdd9bf2f5e25ec6eea4

test:
  secret_key_base: c3b413b7b764c0f9ac5ebb6cfcb23da1349b02ebbbcecf8cbfaa15163491e5b976ddd81c130030cb75e2a9892d743f2d2fa7cd0d682a69826c779524c21f27c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
